/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bandtec.projeto_individual_lp;

import java.awt.Color;
import java.util.concurrent.ThreadLocalRandom;

/**
 *
 * @author Aluno
 */
public class MonitoramentoDeMaquinas extends javax.swing.JFrame {

    /**
     * Creates new form MonitoramentoDeMaquinas
     */
    public MonitoramentoDeMaquinas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pbDado2 = new javax.swing.JProgressBar();
        pbDado1 = new javax.swing.JProgressBar();
        pbDado3 = new javax.swing.JProgressBar();
        lbTexto1 = new javax.swing.JLabel();
        lbTexto2 = new javax.swing.JLabel();
        lbTexto3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jbMaximoCpu = new javax.swing.JLabel();
        jbMedioCpu = new javax.swing.JLabel();
        jbMinimoCpu = new javax.swing.JLabel();
        jbMaximoDisco = new javax.swing.JLabel();
        jbMedioDisco = new javax.swing.JLabel();
        jbMinimoDisco = new javax.swing.JLabel();
        jbMaximoMemoria = new javax.swing.JLabel();
        jbMedioMemoria = new javax.swing.JLabel();
        jbMinimoMemoria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pbDado2.setMaximum(95);
        pbDado2.setMinimum(1);
        pbDado2.setValue(0);

        pbDado1.setMaximum(90);
        pbDado1.setValue(0);

        pbDado3.setMinimum(1);
        pbDado3.setValue(0);

        lbTexto1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTexto1.setText("CPU");

        lbTexto2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTexto2.setText("Disco");

        lbTexto3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTexto3.setText("Memória");

        jButton1.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        jButton1.setText("Fazer leitura de dados");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Monitoramento de recursos");

        jLabel2.setText("Máximo CPU");

        jLabel3.setText("Médio CPU");

        jLabel4.setText("Minimo CPU");

        jLabel5.setText("Máximo Disco");

        jLabel6.setText("Médio Disco");

        jLabel7.setText("Minimo Disco");

        jLabel8.setText("Máximo Memória");

        jLabel9.setText("Médio Memória");

        jLabel10.setText("Minimo Memória");

        jbMaximoCpu.setText("0%");

        jbMedioCpu.setText("0%");

        jbMinimoCpu.setText("0%");

        jbMaximoDisco.setText("0%");

        jbMedioDisco.setText("0%");

        jbMinimoDisco.setText("0%");

        jbMaximoMemoria.setText("0%");

        jbMedioMemoria.setText("0%");

        jbMinimoMemoria.setText("0%");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbMedioCpu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jbMedioDisco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(151, 151, 151)
                        .addComponent(jbMedioMemoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbTexto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pbDado1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pbDado2, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                    .addComponent(lbTexto2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pbDado3, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                    .addComponent(lbTexto3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbMaximoCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbMinimoCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jbMaximoDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbMinimoDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(11, 11, 11)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jbMaximoMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbMinimoMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTexto1)
                    .addComponent(lbTexto2)
                    .addComponent(lbTexto3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pbDado1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pbDado3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pbDado2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jbMaximoCpu))
                    .addComponent(jLabel5)
                    .addComponent(jbMaximoDisco)
                    .addComponent(jLabel8)
                    .addComponent(jbMaximoMemoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jbMedioCpu)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jbMedioDisco)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jbMedioMemoria)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jbMinimoCpu))
                    .addComponent(jbMinimoDisco)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbMinimoMemoria)
                        .addComponent(jLabel10)))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Integer valorMaximoCpu = 90;
        Integer valorMedioCpu;
        Integer valorMinimoCpu = 10;
        
        Integer valorMaximoDisco = 95;
        Integer valorMedioDisco;
        Integer valorMinimoDisco = 15;
        
        Integer valorMaximoMemoria = 90;
        Integer valorMedioMemoria;
        Integer valorMinimoMemoria = 10;
        
        pbDado1.setStringPainted(true);
        pbDado1.setForeground(Color.BLACK);
        
        pbDado2.setStringPainted(true);
        pbDado2.setForeground(Color.BLACK);
        
        pbDado3.setStringPainted(true);
        pbDado3.setForeground(Color.BLACK);
        
        
        Integer cpu = ThreadLocalRandom.current().nextInt(0, 90);
        Integer disco = ThreadLocalRandom.current().nextInt(0, 95);
        Integer memoria = ThreadLocalRandom.current().nextInt(0, 100);
        
        
        pbDado1.setValue(cpu);
        pbDado2.setValue(disco);
        pbDado3.setValue(memoria);
        
        pbDado1.setString(String.format("%d%%",pbDado1.getValue()));
        pbDado2.setString(String.format("%d%%",pbDado2.getValue()));
        pbDado3.setString(String.format("%d%%",pbDado3.getValue()));
        
        if (pbDado1.getValue() > valorMinimoCpu) {
            valorMaximoCpu = pbDado1.getValue();
            jbMaximoCpu.setText(valorMaximoCpu.toString() + "%");
            valorMedioCpu = (valorMaximoCpu+valorMinimoCpu)/2;
            jbMedioCpu.setText(valorMedioCpu.toString() + "%");
        }else{
            valorMinimoCpu = pbDado1.getValue();
            jbMinimoCpu.setText(valorMinimoCpu.toString() + "%");
        }
        
       
        
        if (pbDado2.getValue() > valorMinimoDisco) {
            valorMaximoDisco = pbDado2.getValue();
            jbMaximoDisco.setText(valorMaximoDisco.toString() + "%");
            valorMedioDisco = (valorMaximoDisco+valorMinimoDisco)/2;
            jbMedioDisco.setText(valorMedioDisco.toString() + "%");
        }else{
            valorMinimoDisco = pbDado2.getValue();
            jbMinimoDisco.setText(valorMinimoDisco.toString() + "%");
        }
        
         if (pbDado3.getValue() > valorMinimoMemoria) {
            valorMaximoMemoria = pbDado3.getValue();
            jbMaximoMemoria.setText(valorMaximoMemoria.toString() + "%");
            valorMedioMemoria = (valorMaximoMemoria+valorMinimoMemoria)/2;
            jbMedioMemoria.setText(valorMedioMemoria.toString() + "%");
        }else{
            valorMinimoMemoria = pbDado3.getValue();
            jbMinimoMemoria.setText(valorMinimoMemoria.toString() + "%");
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonitoramentoDeMaquinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonitoramentoDeMaquinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonitoramentoDeMaquinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonitoramentoDeMaquinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonitoramentoDeMaquinas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jbMaximoCpu;
    private javax.swing.JLabel jbMaximoDisco;
    private javax.swing.JLabel jbMaximoMemoria;
    private javax.swing.JLabel jbMedioCpu;
    private javax.swing.JLabel jbMedioDisco;
    private javax.swing.JLabel jbMedioMemoria;
    private javax.swing.JLabel jbMinimoCpu;
    private javax.swing.JLabel jbMinimoDisco;
    private javax.swing.JLabel jbMinimoMemoria;
    private javax.swing.JLabel lbTexto1;
    private javax.swing.JLabel lbTexto2;
    private javax.swing.JLabel lbTexto3;
    private javax.swing.JProgressBar pbDado1;
    private javax.swing.JProgressBar pbDado2;
    private javax.swing.JProgressBar pbDado3;
    // End of variables declaration//GEN-END:variables
}
